var menus=['早餐供应','十全烩饭','早餐新品'];
var lists=[
	{
		"早餐供应":[
			{
				id:1,imgUrl:"../media/images/pic_01.jpg",name:"早餐供应三鲜春卷1",price:"4",unit:"份"
			},
			{
				id:2,imgUrl:"../media/images/pic_01.jpg",name:"早餐供应三鲜春卷2",price:"4",unit:"份"
			},
			{
				id:3,imgUrl:"../media/images/pic_01.jpg",name:"早餐供应三鲜春卷3",price:"4",unit:"份"
			},
			{
				id:4,imgUrl:"../media/images/pic_01.jpg",name:"早餐供应三鲜春卷4",price:"4",unit:"份"
			},
			{
				id:5,imgUrl:"../media/images/pic_01.jpg",name:"早餐供应三鲜春卷5",price:"4",unit:"份"
			},
			{
				id:6,imgUrl:"../media/images/pic_01.jpg",name:"早餐供应三鲜春卷6",price:"4",unit:"份"
			},
			{
				id:7,imgUrl:"../media/images/pic_01.jpg",name:"早餐供应三鲜春卷7",price:"4",unit:"份"
			},
			{
				id:8,imgUrl:"../media/images/pic_01.jpg",name:"早餐供应三鲜春卷8",price:"4",unit:"份"
			},
			{
				id:9,imgUrl:"../media/images/pic_01.jpg",name:"早餐供应三鲜春卷9",price:"4",unit:"份"
			},
			{
				id:10,imgUrl:"../media/images/pic_01.jpg",name:"早餐供应三鲜春卷10",price:"4",unit:"份"
			},
			{
				id:11,imgUrl:"../media/images/pic_01.jpg",name:"早餐供应三鲜春卷11",price:"4",unit:"份"
			}

		]
	},{

		"十全烩饭":[
			{
				id:12,imgUrl:"../media/images/pic_01.jpg",name:"十全烩饭招牌三鲜春卷1",price:"4",unit:"份"
			},
			{
				id:13,imgUrl:"../media/images/pic_01.jpg",name:"十全烩饭招牌三鲜春卷2",price:"4",unit:"份"
			},
			{
				id:14,imgUrl:"../media/images/pic_01.jpg",name:"十全烩饭招牌三鲜春卷3",price:"4",unit:"份"
			},
			{
				id:15,imgUrl:"../media/images/pic_01.jpg",name:"十全烩饭招牌三鲜春卷4",price:"4",unit:"份"
			},
			{
				id:16,imgUrl:"../media/images/pic_01.jpg",name:"十全烩饭招牌三鲜春卷5",price:"4",unit:"份"
			},
			{
				id:17,imgUrl:"../media/images/pic_01.jpg",name:"十全烩饭招牌三鲜春卷6",price:"4",unit:"份"
			},
			{
				id:18,imgUrl:"../media/images/pic_01.jpg",name:"十全烩饭招牌三鲜春卷7",price:"4",unit:"份"
			},
			{
				id:19,imgUrl:"../media/images/pic_01.jpg",name:"十全烩饭招牌三鲜春卷8",price:"4",unit:"份"
			},
			{
				id:20,imgUrl:"../media/images/pic_01.jpg",name:"十全烩饭招牌三鲜春卷9",price:"4",unit:"份"
			},
			{
				id:21,imgUrl:"../media/images/pic_01.jpg",name:"十全烩饭招牌三鲜春卷10",price:"4",unit:"份"
			},
			{
				id:22,imgUrl:"../media/images/pic_01.jpg",name:"十全烩饭招牌三鲜春卷11",price:"4",unit:"份"
			}
		]
	},{

		"早餐新品":[
			{
				id:23,imgUrl:"../media/images/pic_01.jpg",name:"早餐新品招牌三鲜春卷1",price:"4",unit:"份"
			},
			{
				id:24,imgUrl:"../media/images/pic_01.jpg",name:"早餐新品招牌三鲜春卷2",price:"4",unit:"份"
			},
			{
				id:25,imgUrl:"../media/images/pic_01.jpg",name:"早餐新品招牌三鲜春卷3",price:"4",unit:"份"
			},
			{
				id:26,imgUrl:"../media/images/pic_01.jpg",name:"早餐新品招牌三鲜春卷4",price:"4",unit:"份"
			},
			{
				id:27,imgUrl:"../media/images/pic_01.jpg",name:"早餐新品招牌三鲜春卷5",price:"4",unit:"份"
			},
			{
				id:28,imgUrl:"../media/images/pic_01.jpg",name:"早餐新品招牌三鲜春卷6",price:"4",unit:"份"
			},
			{
				id:29,imgUrl:"../media/images/pic_01.jpg",name:"早餐新品招牌三鲜春卷7",price:"4",unit:"份"
			},
			{
				id:30,imgUrl:"../media/images/pic_01.jpg",name:"早餐新品招牌三鲜春卷8",price:"4",unit:"份"
			},
			{
				id:31,imgUrl:"../media/images/pic_01.jpg",name:"早餐新品招牌三鲜春卷9",price:"4",unit:"份"
			},
			{
				id:31,imgUrl:"../media/images/pic_01.jpg",name:"早餐新品招牌三鲜春卷10",price:"4",unit:"份"
			},
			{
				id:32,imgUrl:"../media/images/pic_01.jpg",name:"早餐新品招牌三鲜春卷11",price:"4",unit:"份"
			}
		]
	}
]
