<?php 
interface IMonitorOneDAL{
	public function DoLogin($mobilphone,$serverphone, $password);
	public function checkPwd($shopid,$pwd);
	public function genrPreExcel($shopid, $shopname);
	public function post_curl($url, $params);
	public function getHomeData($shopid);
	public function getUseTabNum($shopid);
	public function saveVipCard($inputarr);
	public function getVipcardList($shopid);
	public function delOneVcd($vcid);
	public function getOneVcdData($vcid);
	public function updateOneVcd($inputarr);
	public function getShopTablesData($shopid);
	public function getTabSByZoneid($zoneid);
	public function getTableStatusNum($shopid);
	public function getTabCounsumeInfo($tabid);
	public function getChargeVipCard($bossid);
	public function chargeForPeople($inputarr);
	public function hasTabsInZone($zoneid);
	public function getDaySheetData($shopid,$theday,$cashierman);
	public function judeFoodDiscountByFoodid($foodid);
	public function getTabNum($shopid);
	public function getTimeSheetData($shopid,$starttime,$endtime);
	public function getTotalmoneyAndFooddisaccountmoney($billid);
	public function getFoodTypes($shopid);
	public function getFoodDataByFtid($shopid,$ftidarr,$starttime,$endtime);
	public function getFoodUpTimeByFoodid($foodid);
	public function array_sort($arr, $keys, $type = 'asc');
	public function getShopRegTime($shopid);
	public function getTypeCalcData($shopid,$starttime,$endtime);
	public function getFoodtypenameByftid($ftid);
	public function getDailySheetData($shopid,$starttime,$endtime,$type);
	public function getTicketNameById($ticketid);
	public function isRegByphone($phone,$shopid);
	public function getUidByphone($phone);
	public function doChargeRecord($inputarr);
	public function getVipAccountMoney($uid,$shopid,$cardid);
	public function getChargeResult($recordid);
	public function getUserinfoByUid($uid);
	public function getVipcardnameByCardid($cardid);
	public function getChargeRecordData($shopid,$starttime,$endtime);
	public function isSendToTheUser($shopid,$uid,$cardid);
	public function getMyVips($bossid,$userphone,$cardid);
	public function getAccountbance($shopid,$uid,$cardid);
	public function consumeByVipcard($inputarr);
	public function minusAccountBlance($shopid,$uid,$cardid,$vippaymoney);
	public function getVipConsumeRecord($viprcid);
	public function getVipPayrecord($shopid,$starttime,$endtime);
	public function getFoodOrderByType($shopid);
	public function getFoodsByFtid($ftid);
	public function getFoodUpTime($foodid);
	public function updateFoodData($foodid, $newfoodpic,$timestamp);
	public function getOneBillDataByBillid($billid);
	public function getOpenHourByShopid($shopid);
	public function getIndexPageData($shopid);
	public function getShopInfo($shopid);
	public function getShopTypenameByShoptye($shoptype);
	public function getServersByShopid($shopid);
	public function getBillStatisticByServerid($shopid,$uid,$theday);
	public function getTheday($shopid);
	public function getSignDetails($shopid);
	public function delOneBillByBillid($billid);
	public function judgePhoneInMyShopid($userphone,$shopid);
	public function isServerInMyShop($shopid,$uid);
	public function getFoodinfoByFoodid($foodid);
	public function getDaliAccount($shopid);
	public function getAgentAccountByAgentid($agentid);
	public function addToDaliAccount($shopid, $income);
	public function getAgentIncome($agentid);
	public function buyAccountRecord($inputarr);
	public function getBuyAccountRecord($buyid);
	public function addShopUseAccount($inputarr);
	public function getShopuseaccountEndtime($shopid);
	public function getShopaccounttype($shopid);
	public function getBuyAccountRecords($shopid);
	public function getDonateRecords($shopid);
	public function discountOneFood($billid,$foodid,$discountval);
	public function getTablenameByTabid($tabid);
	public function getPayPageData($billid, $shopid);
	public function getOneDesposit($billid);
	public function getDepositmoney($shopid);
	public function getAddBillOrderData($shopid,$starttime,$endtime);
	public function getQrcodeRecordData($shopid,$starttime,$endtime);
	public function getDaysSheetData($shopid, $startdate, $enddate);
	public function addCusSheetAdvData($shopid,$content,$advurl);
	public function getCusSheetAdvData($shopid);
	public function delOneAdvByAdvid($advid);
	public function getZonenameByZoneid($zoneid);
	public function getFtnameByFtid($ftid);
	public function getCashierMan($shopid);
	public function getTabStatusByTabid($tabid);
	public function getSwitchPayerTime($shopid);
	public function getTopClearmoney($shopid);
	public function getServername($shopid, $uid);
	public function hasBillBeforeTheTab($shopid, $tabid,$timestamp);
	public function updateBillFood($foodarr,$billid, $returnnum, $foodid,$foodnum,$cooktype);
	public function getFoodsByBillid($billid);
	public function getOrginbillTime($orignbillid);
	public function changeShowtypeStatus($ftid,$status);
	public function getServerIdByServerphone($userphone);
	public function isTheShopServerByUid($shopid,$uid);
	public function isTheServerManager($roleid);
	public function getAllTickets($shopid);
	public function getFootypeImgUptime($ftid);
	public function updateFoodtypeData($ftid, $newfypepic,$timestamp);
	public function getTablesData($shopid);
	public function getPrinternameByPid($pid);
	public function getZonesByShopid($shopid);
	public function getOneTableData($tabid,$typeno);
	public function saveOneTable($inputarr);
	public function updateOneTable($tabid,$inputarr);
	public function delOneTableData($tabid);
	public function generTabQrcodeImg($inputarr);
	public function getCardrate($cardid);
	public function doMobilphoneLogin($mobilphone,$passwd);
	public function getManagerRoleid($shopid);
	public function getTabdataByShopid($shopid);
	public function delOneBerforeBill($beforebillid);
	public function getFoodsByBeforeBillid($billid);
	public function getMyvipinfo($shopid,$cardno);
	public function consumeVipMoney($shopid,$cardno,$money);
	public function intoVipConsumeRecord($inputarr);
	public function getBossidByShopid($shopid);
	public function getWechatUserinfo($uid);
	public function getUnPayCheckData($shopid);
	public function getUnpaidSheetData($billid);
	public function recoverStockByBilid($Billid);
	public function recoverStock($foodid,$num);
	public function getShopnameByBillid($billid);
}
?>