<?php 
interface IMonitorSixDAL{
	public function getFoodidsData($shopid);
	public function getFoodidsByFtid($ftid);
	public function getFoodsTrendsData($shopid,$datearr,$foodidarr, $thehour);
	public function getTurnfoodTrendData($shopid,$startdate,$enddate,$datearr,$thehour);
	public function getCusnumTrendData($shopid,$startdate,$enddate,$datearr,$thehour);
	public function getCusnumRealTrendData($inputarr);
	public function getFoodSoldByTypeData($inputarr);
	public function getOneUnpayBill($uid);
	public function getShopInfo($shopid);
	public function getTabnameByTabid($tabid);
	public function getUserphoneByuid($uid);
	public function getCoupontypesByShopid($shopid);
	public function getOneCouponByCpid($cpid);
	public function addOneCoupon($inputarr);
	public function updateOneCoupon($cpid,$inputarr);
	public function delOneCoupon($cpid);
	public function getRolesData($shopid);
	public function getOneRoleData($roleid);
	public function changeOneRole($roleid,$type,$status);
	public function addOneRoleData($inputarr);
	public function delOneRoleByRoleid($roleid);
	public function getShopServers($shopid);
	public function getOneServerByServerid($serverid);
	public function addOneServer($inputarr);
	public function updateOneServer($serverid,$inputarr);
	public function delOneServerByServerid($serverid);
	public function addPreConsumeBill($inputarr);
	public function getPreBillByBillid($billid);
	public function isMyBindPhone($uid,$shopid);
	public function getMyVipMoney($shopid,$uid);
	public function updateMyvipAccount($inputarr);
	public function getOneVcdData($vcid);
	public function vipPayrecord($inputarr);
	public function getCardid($shopid,$uid);
	public function delPrebillByBillid($billid);
	public function getUidByPhone($phone);
	public function getZonesByShopid($shopid);
	public function getOnezoneByZoneid($zoneid);
	public function delOneZoneByZoneid($zoneid);
	public function updateOneZone($inputarr);
	public function addOneZone($inputarr);
	public function isShowVipPay($uid,$shopid);
	public function getFoodinfo($shopid);
	public function sortfoodData($arr);
	public function getPwdByUid($uid);
	public function saveOneTag($inputarr);
	public function updateOneTag($viptagid,$inputarr);
	public function getOneTagByTagid($viptagid);
	public function delOneTagByTagid($viptagid);
	public function getViptagsData($bossid);
	public function getBorthershopByShopid($shopid);
	public function getFoodtypeByShopid($shopid);
	public function DoCopyMenuData($inputarr);
	public function getZoneIdByShopid($shopid);
	public function array_sort($arr, $keys, $type = 'asc');
	public function setShopaccountData($shopid,$op,$val);
	public function getShopaccountData($shopid);
	public function getUpTime($shopid);
	public function updateAccountData($shopid, $op,$newpic,$timestamp);
	public function saveShopAccount($inputarr);
	public function updateShopAccount($inputarr);
	public function getShopAcountData($shopid);
	public function bindShopidAndOpenid($shopid,$openid);
	public function getShopidByOpenid($openid);
	public function ImageSetSize($imgurl,$width,$height);
	public function getRealOpenidByShopid($shopid);
	public function getShopmoneyByShopid($shopid);
	public function getTodayMoney($shopid);
	public function addTransferLog($inputarr);
	public function updateShoperAccount($shopid,$account);
	public function getShopidByPhoneAndPwd($phone,$passwd);
	public function setPaidBillData($inputarr);
	public function getPaidBillData($billid);
	public function sendSmsEmerg($billid);
	public function getPhoneByBillid($billid);
	public function getOpenidByuid($uid);
	public function getPhoneByOpenid($openid);
	public function sendSMSBillInfo($billid,$op);
	public function getOneBillShopinfo($tab, $billid);
	public function getAreaByBillid($billid);
	public function getManagerPhone($area);
}
?>