<?php 
interface IWorkerDAL{
	public function getTablenameByTabid($tabid);
	public function getTheTabPaid($tabid,$shopid);
	public function createVirtualTab($inputarr);
	public function getTabInfoByTabid($tabid);
	public function getVirtualTabnum($tabid);
	public function getOneBillByBillid($billid,$token);
	public function getCusInfo($uid,$shopid);
	public function getShopInfo($shopid);
	public function isServer($uid,$shopid);
	public function updateBillFood($foodarr, $billid,$returnnum,$foodid,$foodnum,$cooktype);
	public function printReturnOrder($inputarr);
	public function getTheShopPrinters($foodid);
	public function getPrinterInfoByZonid($zoneid);
	public function getPrinterInfoByPid($pid);
	public function getPrintContent($inputarr, $deviceno,$devicekey);
	public function getPrintSmallContent($inputarr, $deviceno,$devicekey);
	public function addToReturnBill($inputarr);
	public function getOneFoodInBill($billid,$foodid);
	public function confrimFoodAmount($billid,$foodid,$foodamount,$foodnum,$cooktype);
	public function doDonateFood($billid,$foodid,$donatenum,$foodnum,$cooktype);
	public function updateOneTabStatus($tabid,$tabstatus);
	public function swithTable($billid, $tabid,$newtabname);
	public function updateTabStatus($newtabid,$oldtabid,$oldtabstatus);
	public function getPrinterListByShopid($shopid);
	public function getPrintersInfoByPrinterarr($printerarr);
	public function getOneBillInfoByBillid($billid);
	public function intoConsumeRecord($inputdarr);
	public function getDonateInfoByShopid($shopid,$foodarr);
	public function getFoodInfoByFoodid($foodid);
	public function getZoneNameByZoneid($zoneid);
	public function getBillPackarr($billid,$package);
	public function getPackNum($billid,$pkid);
	public function getPackFoodNum($pkid,$foodid);
	public function getPayPageData($billid,$shopid);
	public function getTotalmoneyAndFoodDiscountmoney($billid);
	public function judgeTheFoodDisaccount($foodid);
	public function getPackHistoryData($billid,$pkid);
	public function getBillidByTabid($shopid,$tabid,$token);
	public function addOrderToOldBill($oldbillid,$foodarr);
	public function getOldTabstatusByTabid($tabid);
	public function getPacknameByPkid($pkid);
	public function updateFoodsToBill($billid,$foodarr);
	public function getBillTypeData($billid,$outputtype);
	public function getPrinteridByFtid($ftid);
	public function getOutputypeByPid($pid);
	public function getFtidByFoodid($foodid);
	public function getTabStatusByTabid($tabid);
	public function ChangeTableSheetContent($shopid,$oldtabname,$newtabname);
	public function getChangeTabPrintContent($oldtabname,$newtabname,$printerarr);
	public function getChangeTabSmallPrintContent($oldtabname,$newtabname,$printerarr);
	public function getShopAllPrinters($shopid);
	public function getShopidByBillid($billid);
	public function addDespositData($billid,$depositmoney);
	public function getOneDesposit($billid);
	public function getDepositmoney($shopid);
	public function switchOneFoodBehavior($foodid,$foodamount,$cooktype,$oldbillid,$tabid);
	public function getStartBillidByTabid($tabid);
	public function addSwitchFoodRecordData($oldbillid,$foodid,$foodamount,$tabid,$timestamp);
	public function getBillPaystatusByBillid($billid);
	public function intoChangeTabRecord($record);
	public function getUrgeContentData($inputarr);
	public function getUrgeContent($inputarr,$deviceno,$devicekey);
	public function getUrgeSmallContent($inputarr,$deviceno,$devicekey);
	public function updateBillDeposit($billid,$newdeposit);
	public function saveUpdateTabStatus($inputarr);
	public function getShopidByTabid($tabid);
	public function updateSelfStockByReturnFood($foodid,$returnnum);
	public function judgeAutoStock($foodid);
	public function getLastbillidByTabid($shopid,$tabid);
	public function isTheShopServerRoleidByUid($shopid,$uid);
	public function getRoleFunsByRoleid($roleid);
	public function addBillRecordData($inputarr);
	public function getMustOrderMenuData($shopid,$cusnum);
	public function getPacksData($shopid,$foodarr);
	public function addUidToBill($billid,$uid);
	public function getBeforeBillData($shopid,$uid,$type);
	public function getBillData($shopid,$uid,$type);
	public function intoBeforebillConsumeRecord($inputdarr);
	public function addUidToBeforeBill($beforebillid, $uid);
	public function updateFoodsToBeforeBill($beforebillid, $packarr);
	public function addOrderToOldBeforeBill($oldbeforebillid, $foodarr);
	public function getOneBillInfoByBeforeBillid($oldbeforebillid);
	public function updateBillData($inputarr);
	public function getOnefoodinfoByFoodid($foodid);
	public function printReplaceOrder($inputarr);
	public function getReplaceFoodContent($inputarr,$deviceno,$devicekey);
	public function getReplaceFoodSmallContent($inputarr,$deviceno,$devicekey);
	public function addReplacefoodRecord($inputarr);
	public function addOnefoodToBill($billid,$onefood);
	public function getBillAndPayStatus($billid);
	public function getTabidByBillid($billid);
	public function getBillinfoByTabid($tabid);
	public function delOneBillByBillid($billid);
	public function getShopidByTabidData($tabid);
	public function hasNewbillbyTabid($billid,$tabid);
	public function updateFoodStatus($billid,$foodarr,$foodid,$foodstatus,$foodamount,$cooktype);
	public function getTopClearmoney($shopid);
	public function getPayRight($uid,$shopid);
	public function updateBillCusnum($billid,$cusnum);
	public function updateSelfStock($foodarr);
	public function updateSelfStocknum($foodid,$foodamount);
	public function getPayStatusByBillid($billid);
	public function updateBeforeBillFood($foodarr,$billid, $returnnum, $foodid,$foodnum,$cooktype);
	public function getOneFoodInBeforeBill($billid,$foodid);
	public function delOneBerforeBill($beforebillid);
	public function removeEmoji($text);
	public function SetNewPrice($billid,$foodid,$foodarr,$cooktype,$foodnum,$newprice);
	public function printSwitchSheet($inputarr);
	public function generSwitchSheet($inputarr,$deviceno,$devicekey);
	public function generSwitchSmallSheet($inputarr,$deviceno,$devicekey);
	public function findThePrinter($shopid, $outputtype);
	public function getMatchFoodInfo($foodarr,$foodid,$foodamount,$cooktype);
	public function addBillnumData($billid,$billnum);
	public function getMyBillData($tabid,$shopid);
	public function getServeridByUid($shopid,$uid);
	public function updateMoneyWhenReturnfood($billid,$returnmoney);
	public function getWechatUserinfo($uid);
	public function emoji2str($str);
	//更新库存月表
	public function addStockin($data);
}
?>